name: Build Kernel with KernelSU
 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout KernelSU
        uses: actions/checkout@v4
        with:
          repository: KernelSU/KernelSU
          path: kernelsu

      - name: Clone Kernel source
        run: |
          git clone --depth=1 -b chromeos-6.6 https://chromium.googlesource.com/chromiumos/third_party/kernel kernel

      - name: Inject KernelSU into kernel tree
        run: |
          cd kernel
          # 挂载 KernelSU 到 drivers/kernelsu
          ln -sf ../../kernelsu drivers/kernelsu

          # 修改 drivers/Makefile
          grep -q 'kernelsu' drivers/Makefile || echo 'obj-$(CONFIG_KSU) += kernelsu/' >> drivers/Makefile

          # 修改 drivers/Kconfig
          grep -q 'kernelsu/Kconfig' drivers/Kconfig || echo 'source "drivers/kernelsu/Kconfig"' >> drivers/Kconfig

          # 在 arch/x86/configs/x86_64_defconfig 里加 CONFIG_KSU
          DEFCONF=arch/x86/configs/x86_64_defconfig
          grep -q 'CONFIG_KSU' $DEFCONF || echo 'CONFIG_KSU=m' >> $DEFCONF

          echo "==== [DEBUG] defconfig 内容 ===="
          cat $DEFCONF

      - name: Build kernel with LLVM
        run: |
          cd kernel
          export DEFCONFIG=x86_64_defconfig
          echo "==== [DEBUG] 清理环境 ===="
          make LLVM=1 LLVM_IAS=1 O=${PWD} mrproper

          echo "==== [DEBUG] 生成 defconfig ===="
          make LLVM=1 LLVM_IAS=1 O=${PWD} ${DEFCONFIG} < /dev/null
          echo "==== [DEBUG] 生成后的 .config（defconfig 阶段） ===="
          grep KSU .config || echo "KSU not found yet"

          echo "==== [DEBUG] 调整配置 ===="
          scripts/config --file .config \
            -e MODULES \
            -e MODULE_UNLOAD \
            -m KSU \
            -d MODULE_SIG \
            -d MODULE_SIG_ALL \
            -e LTO_CLANG \
            -d LTO_NONE \
            -e LTO_CLANG_THIN

          echo "==== [DEBUG] 运行 olddefconfig ===="
          yes "" | make O=${PWD} olddefconfig

          echo "==== [DEBUG] 最终 .config 检查 ===="
          grep KSU .config || { echo "CONFIG_KSU not set!"; exit 1; }
