name: Build FydeOS KernelSU LKM (x86_64)
on:
  push:
    branches: ["main", "ci", "dev"]
    paths:
      - ".github/workflows/build-fydeos-lkm.yml"
      - "kernel/**"
      - "drivers/kernelsu/**"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/build-fydeos-lkm.yml"
      - "kernel/**"
      - "drivers/kernelsu/**"
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable debug mode"
        type: boolean
        default: false

env:
  git_tag: chromeos-5.15

jobs:
  build-lkm:
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request' && !github.event.pull_request.draft)
    name: Build FydeOS x86_64 KernelSU LKM
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      actions: read

    env:
      LTO: thin
      KERNEL_DIR: ${{ github.workspace }}/kernel

    steps:
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null
          df -h

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            bc bison build-essential ca-certificates flex git gnupg \
            libelf-dev libssl-dev lsb-release software-properties-common wget \
            libncurses-dev binutils-x86-64-linux-gnu gcc-x86-64-linux-gnu \
            rsync python3 device-tree-compiler kmod

          sudo ln -s --force python3 /usr/bin/python

          export LLVM_VERSION=14
          # 增加下载重试机制和备用源
          for i in {1..3}; do
            if wget --timeout=30 https://apt.llvm.org/llvm.sh; then
              echo "Successfully downloaded llvm.sh from main source"
              break
            else
              echo "Attempt $i failed, trying backup source..."
              if wget --timeout=30 https://raw.githubusercontent.com/llvm/llvm-project/main/llvm/utils/release/llvm.sh; then
                echo "Successfully downloaded llvm.sh from backup source"
                break
              fi
            fi
            if [ $i -eq 3 ]; then
              echo "Error: Failed to download llvm.sh after 3 attempts"
              exit 1
            fi
          done

          chmod +x llvm.sh
          sudo ./llvm.sh $LLVM_VERSION
          rm ./llvm.sh
          # 链接工具链
          for tool in clang ld.lld llvm-objdump llvm-ar llvm-nm llvm-strip llvm-objcopy llvm-readelf clang++; do
            sudo ln -s --force /usr/bin/$tool-$LLVM_VERSION /usr/bin/$tool
          done

      - name: Checkout KernelSU
        uses: actions/checkout@v4
        with:
          path: KernelSU
          fetch-depth: 0

      - name: Setup kernel source
        run: |
          git clone --depth=1 --branch ${{ env.git_tag }} \
            https://chromium.googlesource.com/chromiumos/third_party/kernel \
            || { echo "Clone failed, retrying..."; git clone --depth=1 --branch ${{ env.git_tag }} https://chromium.googlesource.com/chromiumos/third_party/kernel; }

      - name: Extract kernel version
        working-directory: kernel
        run: |
          VERSION=$(grep -E '^VERSION = ' Makefile | awk '{print $3}')
          PATCHLEVEL=$(grep -E '^PATCHLEVEL = ' Makefile | awk '{print $3}')
          SUBLEVEL=$(grep -E '^SUBLEVEL = ' Makefile | awk '{print $3}')
          echo "Kernel version: $VERSION.$PATCHLEVEL.$SUBLEVEL"
          echo "version=$VERSION.$PATCHLEVEL.$SUBLEVEL" >> $GITHUB_ENV

      - name: Setup KernelSU (as module)
        working-directory: kernel
        run: |
          KERNEL_ROOT=$GITHUB_WORKSPACE/kernel
          echo "[+] Kernel root: $KERNEL_ROOT"

          ln -sf $GITHUB_WORKSPACE/KernelSU/kernel $KERNEL_ROOT/drivers/kernelsu

          DRIVER_MAKEFILE=$KERNEL_ROOT/drivers/Makefile
          DRIVER_KCONFIG=$KERNEL_ROOT/drivers/Kconfig
          grep -q "kernelsu" "$DRIVER_MAKEFILE" || printf "\nobj-\$(CONFIG_KSU) += kernelsu/\n" >> "$DRIVER_MAKEFILE"
          grep -q "kernelsu" "$DRIVER_KCONFIG" || sed -i "/endmenu/i\\source \"drivers/kernelsu/Kconfig\"" "$DRIVER_KCONFIG"

          KSU_KCONFIG=$KERNEL_ROOT/drivers/kernelsu/Kconfig
          sed -i 's/bool "KernelSU support"/tristate "KernelSU support"/' $KSU_KCONFIG
          sed -i 's/default y/default m/' $KSU_KCONFIG

          sed -i 's/-dirty//g' $KERNEL_ROOT/scripts/setlocalversion

          cd $GITHUB_WORKSPACE/KernelSU
          KSU_VERSION=$(($(git rev-list --count HEAD) + 10200))
          echo "KernelSU version: $KSU_VERSION"
          echo "kernelsu_version=$KSU_VERSION" >> $GITHUB_ENV

      - name: Configure kernel for modules
        working-directory: kernel
        run: |
          export DEFCONFIG=x86_64_defconfig
          make LLVM=1 LLVM_IAS=1 O=${PWD} mrproper
          make LLVM=1 LLVM_IAS=1 O=${PWD} ${DEFCONFIG} < /dev/null
          scripts/config --file .config \
            -e MODULES \
            -e MODULE_UNLOAD \
            -e KSU \
            -d MODULE_SIG \
            -d MODULE_SIG_ALL \
            -e LTO_CLANG -d LTO_NONE -e LTO_CLANG_THIN

      - name: Build kernel and LKM
        working-directory: kernel
        run: |
          # 第一步：优先编译内核核心（生成 vmlinux.symvers 符号文件）
          echo "=== Compiling kernel core (vmlinux) to generate symbols ==="
          timeout 3600 make LLVM=1 LLVM_IAS=1 O=${PWD} -j$(nproc) vmlinux
          
          # 第二步：基于生成的符号文件编译模块
          echo "=== Compiling kernel modules (using vmlinux.symvers) ==="
          timeout 3600 make LLVM=1 LLVM_IAS=1 O=${PWD} -j$(nproc) modules
          
          # 检查关键文件是否生成（解决符号缺失和 modules.builtin 问题）
          if [ ! -f "vmlinux.symvers" ]; then
            echo "Error: vmlinux.symvers not found! Kernel core compilation failed."
            exit 1
          fi
          if [ ! -f "modules.order" ]; then
            echo "Error: modules.order not found! Module compilation failed."
            exit 1
          fi
          if [ ! -f "modules.builtin" ]; then
            echo "Error: modules.builtin not found! Module compilation failed."
            exit 1
          fi
          
          # 第三步：编译内核镜像（bzImage）
          echo "=== Compiling kernel image (bzImage) ==="
          timeout 3600 make LLVM=1 LLVM_IAS=1 O=${PWD} -j$(nproc) bzImage
          
          # 第四步：安装模块到本地目录
          echo "=== Installing modules to local directory ==="
          mkdir -p ./modules
          timeout 3600 make LLVM=1 LLVM_IAS=1 O=${PWD} -j$(nproc) \
            INSTALL_MOD_PATH=./modules modules_install
          
          # 确认 KernelSU 模块路径
          echo "ko_path=${PWD}/drivers/kernelsu/kernelsu.ko" >> $GITHUB_ENV

      - name: Verify LKM
        run: |
          if [ ! -f "${{ env.ko_path }}" ]; then
            echo "Error: kernelsu.ko not found!"
            exit 1
          fi
          modinfo ${{ env.ko_path }}

      - name: Upload kernelsu.ko
        uses: actions/upload-artifact@v4
        with:
          name: kernelsu-ko-fydeos-x86_64-${{ env.version }}-ksu${{ env.kernelsu_version }}
          path: ${{ env.ko_path }}
          retention-days: 14
