      - name: Fix Kconfig syntax and integrate KernelSU
        working-directory: kernel
        run: |
          rm -rf drivers/kernelsu
          ln -sf $GITHUB_WORKSPACE/KernelSU/kernel drivers/kernelsu
          
          if [ ! -d "drivers/kernelsu" ]; then
            echo "Error: drivers/kernelsu directory missing!"
            exit 1
          fi
          KSU_KCONFIG=drivers/kernelsu/Kconfig
          if [ ! -f "$KSU_KCONFIG" ]; then
            echo "Error: $KSU_KCONFIG missing!"
            exit 1
          fi
          
          # Create the Kconfig file with proper formatting
          cat << 'EOF' > "$KSU_KCONFIG"
config KSU
	tristate "KernelSU support"
	default m
	depends on MODULES
	help
	  Enable kernel-level root privileges on Android System.
	  To compile as a module, choose M here: the
	  module will be called kernelsu.

config KSU_DEBUG
	bool "KernelSU debug mode"
	depends on KSU
	default n
	help
	  Enable KernelSU debug mode.
EOF
          
          DRIVER_KCONFIG=drivers/Kconfig
          sed -i '/source "drivers\/kernelsu\/Kconfig"/d' "$DRIVER_KCONFIG"
          echo 'source "drivers/kernelsu/Kconfig"' >> "$DRIVER_KCONFIG"
          if ! grep -q 'source "drivers/kernelsu/Kconfig"' "$DRIVER_KCONFIG"; then
            echo "Error: Failed to add Kconfig source entry!"
            exit 1
          fi
          
          DRIVER_MAKEFILE=drivers/Makefile
          sed -i '/obj-$(CONFIG_KSU) += kernelsu\//d' "$DRIVER_MAKEFILE"
          echo 'obj-$(CONFIG_KSU) += kernelsu/' >> "$DRIVER_MAKEFILE"
          if ! grep -q 'obj-$(CONFIG_KSU) += kernelsu/' "$DRIVER_MAKEFILE"; then
            echo "Error: Failed to add Makefile entry!"
            exit 1
          fi